/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-primary-container": "#a5c5ff",
              "on-primary": "#ffffff",
              "on-tertiary-fixed-variant": "#004f58",
              "on-tertiary-container": "#00d8f0",
              "tertiary-fixed": "#9cf0ff",
              "surface-container-lowest": "#ffffff",
              "surface-container-high": "#e6e8ea",
              "error-container": "#ffdad6",
              "on-secondary-fixed": "#001b3c",
              "surface-container": "#eceef0",
              "on-surface-variant": "#424751",
              "surface-variant": "#e0e3e5",
              "secondary-fixed": "#d5e3ff",
              "primary-fixed": "#d6e3ff",
              "tertiary-container": "#005a65",
              "surface-dim": "#d8dadc",
              "primary-container": "#00509e",
              "tertiary-fixed-dim": "#00daf3",
              "on-secondary-container": "#294f83",
              "on-primary-fixed": "#001b3d",
              "surface-tint": "#1f5eac",
              "on-primary-fixed-variant": "#00468b",
              "inverse-surface": "#2d3133",
              "surface-bright": "#f7f9fb",
              "outline": "#727782",
              "on-error": "#ffffff",
              "on-tertiary": "#ffffff",
              "secondary-container": "#9fc2fe",
              "surface": "#f7f9fb",
              "surface-container-highest": "#e0e3e5",
              "background": "#f7f9fb",
              "secondary": "#3a5f94",
              "on-secondary": "#ffffff",
              "on-tertiary-fixed": "#001f24",
              "outline-variant": "#c2c6d3",
              "error": "#ba1a1a",
              "on-error-container": "#93000a",
              "primary-fixed-dim": "#a9c7ff",
              "tertiary": "#004149",
              "inverse-on-surface": "#eff1f3",
              "surface-container-low": "#f2f4f6",
              "on-secondary-fixed-variant": "#1f477b",
              "on-surface": "#191c1e",
              "on-background": "#191c1e",
              "primary": "#003974",
              "secondary-fixed-dim": "#a7c8ff",
              "inverse-primary": "#a9c7ff"
      },
      "fontFamily": {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
